"use client";
import "../globals.css";
import Head from "next/head.js";

// export const metadata = {
//   title: "113年基隆市政府地方產業創新研發推動計畫-地方型SBIR",
//   description: "Generated by 數位燈塔",
// };

// export const revalidate = 0;
// export const fetchCache = "force-no-store";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>113年基隆市政府地方產業創新研發推動計畫-地方型SBIR</title>
        <meta name="description" content="Generated by 數位燈塔" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Siteicon.png" />
        <meta charSet="utf-8" />
        <meta name="description" content="Generated by 數位燈塔" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta
          name="og:title"
          content="112年度基隆市政府地方產業創新研發推動計畫（地方型SBIR）"
        />
        <meta name="og:description" content="最高補助200萬元" />
        <meta
          name="og:image"
          content="https://sbir2023.s3.ap-southeast-2.amazonaws.com/sbir%E5%BE%B5%E4%BB%B6%E8%AA%AA%E6%98%8E%E6%9C%83.png"
        />
        <meta
          property="og:image"
          content="https://sbir2023.s3.ap-southeast-2.amazonaws.com/sbir%E5%BE%B5%E4%BB%B6%E8%AA%AA%E6%98%8E%E6%9C%83.png"
        />
        <meta
          property="og:title"
          content="113年度基隆市政府地方產業創新研發推動計畫-地方型SBIR"
        />
        <meta property="og:description" content="最高補助200萬元" />
      </head>
      <body>
        <div className="w-screen h-screen">{children}</div>
      </body>
    </html>
  );
}
